version: 2

defaults: &defaults
  working_directory: /go/src/github.com/mercari/certificate-expiry-monitor-controller

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.11

jobs:
  build:
    <<: *golang
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dpendency tool
          command: |
            go get -u github.com/golang/dep/cmd/dep
      - run:
          name: Install dependencies
          command: |
            make dep
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/mercari/certificate-expiry-monitor-controller/vendor
      - persist_to_workspace:
          root: /go/src/github.com/mercari/certificate-expiry-monitor-controller
          paths:
            - "vendor/*"
      - run:
          name: Check compilation
          command: |
            make build
  check:
    <<: *golang
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/mercari/certificate-expiry-monitor-controller
      - run:
          name: Install dpendency tool
          command: |
            go get -u golang.org/x/lint/golint
      - run:
          name: Run go vet
          command: |
            make vet
      - run:
          name: Run golint
          command: |
            make lint
      - run:
          name: Run test and collect coverages
          command: |
            make coverage
      - run:
          name: Upload coverages to codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - check:
          requires:
            - build
