version: 2

defaults: &defaults
  working_directory: /go/src/github.com/mercari/certificate-expiry-monitor-controller

golang: &golang
  <<: *defaults
  docker:
    - image: golang:1.19

jobs:
  build:
    <<: *golang
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            go mod download
      - run:
          name: Check compilation
          command: |
            make build
  check:
    <<: *golang
    steps:
      - checkout
      - attach_workspace:
          at: /go/src/github.com/mercari/certificate-expiry-monitor-controller
      - run:
          name: Install dpendency tool
          command: |
            go get -u golang.org/x/lint/golint
      - run:
          name: Run go vet
          command: |
            make vet
      - run:
          name: Run golint
          command: |
            make lint
      - run:
          name: Run test and collect coverages
          command: |
            make coverage
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - check:
          requires:
            - build
